qnas = [{'anwsers': ['Napetost na njem je sorazmerna toku.',
              'Napetost na njem je sorazmerna spremembi toka.',
              'Tok na njem je sorazmeren spremembi napetosti.',
              'Tok na njem je sorazmeren integralu napetosti.'],
  'correct': 2,
  'question': 'Kako deluje kondenzator?'},
 {'anwsers': ['20V',
              '60V',
              '"15V ( U = R * I; R = R1R2 / (R1 + R2) ali z uporabo tokovnega '
              'delilnika ... )"',
              '5V'],
  'correct': 2,
  'question': 'Tok 10mA se razdeli na vzporedni veji z R1 = 2kΩ in R2 = 6kΩ. '
              'Kolikšna je napetost v obeh vejah?'},
 {'anwsers': ['Za 90°.',
              'Za 180°.',
              'Za 45°.',
              'Za -90°. (Napetost na tuljavi prehiteva tok za 90 °)'],
  'correct': 3,
  'question': 'Za koliko se fazi toka in napetosti na tuljavi razlikujeta (ϕi '
              '- ϕu)?'},
 {'anwsers': ['Absolutna vrednost Zk narašča, faza pa upada.',
              'Absolutna vrednost Zk in faza upadata.',
              'Absolutna vrednost Zk upada, faza pa je konstantna.',
              'Absolutna vrednost Zk narašča, faza pa je konstantna.'],
  'correct': 2,
  'question': 'Na RC-liniji s povečevanjem frekvence:'},
 {'anwsers': ['30%', '33%', '36% ( (1+2+1) / (7 + 4) = 36 %)', '39%'],
  'correct': 2,
  'question': 'Koliko % znaša režija (overhead) pri RS-232, če je 7 '
              'podatkovnih bitov in 2 stop bita, uporabljamo pa tudi '
              'pariteto?'},
 {'anwsers': ['Zakaj pa jih ne bi?',
              'Zaradi hitrosti.',
              'Ker PCI standard prekinitev ne obravnava.',
              'Da je njihov nabor lahko večji.'],
  'correct': 2,
  'question': 'Zakaj PCI uporablja serializirane prekinitve?'},
 {'anwsers': ['Ker se poveča napetost na linijah D+ in D-.',
              'Ker se zmanjša napetost na liniji D+ ali D-.',
              'Ker se zmanjša napetost na linijah D+ in D-.',
              'Ker se poveča napetost na liniji D+ ali D-. (D+ za FS, D- za '
              'LS)'],
  'correct': 3,
  'question': 'Kako USB hub ugotovi, da se je naprava priklopila?'},
 {'anwsers': ['"Debelejša žica ima večjo upornost kot tanjša. (NI; velja ravno '
              'obratno)"',
              '"Pri neskončni frekvenci je tuljava kratek stik. (NI; tuljava '
              'je OS)"',
              'Odskok mase je posledica simetrije vodnikov.',
              'Sistem 2. reda vedno niha. (NI: Obstaja sistem 2. reda, ki ne '
              'niha)'],
  'correct': 2,
  'question': 'Katera trditev je pravilna?'},
 {'anwsers': ['0.5V',
              '-0.866V (cos(2*pi*100*0.005 + 30*pi/180))',
              '0.866V',
              '-0.5V/Hz°ms.'],
  'correct': 1,
  'question': 'Kolikšna je vrednost signala u(t) = 1V*cos(ωt+ϕ) pri f = 100Hz '
              'in fazi 30° v času t=5ms?'},
 {'anwsers': ['Tok je konstanten.',
              '"Tok linearno raste. ( u(t) = L * ( di(t) / dt ); i(t) = i(0) + '
              '( 1 / L ) *  integrate[u(t) dt] 0 - t)"',
              'Tok raste s kvadratom.',
              'Tok upada.'],
  'correct': 1,
  'question': 'Kakšen je potek toka na tuljavi, če je napetost na njej '
              'konstantna?'},
 {'anwsers': ['arctg(40/500)',
              'arctg(500/40)',
              '90°.',
              'Odvisno od drugih dejavnikov. (ni podane frekvence)'],
  'correct': 3,
  'question': 'Kolikšna je faza zaporedne vezave upora 500Ω in induktivnosti '
              '40μH?'},
 {'anwsers': ['0.5 V.',
              '"4.5 V. ( napetost je enaka napetosti na drugem bremenu U = Ug '
              '* Rb / (Rb + Rg) ); "',
              '5 V.',
              'Ne moremo ugotoviti.'],
  'correct': 1,
  'question': 'Kolikšna je napetost na sponkah generatorja 5V z notranjo '
              'upornostjo 10Ω, na katerega je priključeno breme 90Ω?'},
 {'anwsers': ['60 Ω',
              '100 Ω (Zk = sqrt ( (R + jwL) / (G + jwC ) )',
              '120 Ω * e^{-j15°}',
              '120 Ω * e{j15°}'],
  'correct': 1,
  'question': 'Kolikšna je karakteristična impedanca linije (R=50mΩ/m, '
              'L=500nH/m, C=50pF/m, G=0) pri 4MHz?'},
 {'anwsers': ['Pri visokih frekvencah se poveča prevodnost vodnika.',
              'Pri visokih frekvencah se poveča upornost vodnika.',
              'Pri visokih frekvencah se tok izogiba površine vodnika.',
              'Posledica prekomernega sončenja.'],
  'correct': 1,
  'question': 'Kaj je kožni pojav?'},
 {'anwsers': ['20 oz. 10.', '25 oz. 9.', '22 oz. 8.', '20 oz. 6.'],
  'correct': 1,
  'question': 'Koliko pinov imajo priključki za serijski vmesnik RS-232C?'},
 {'anwsers': ['R = R | (0x1 << n)',
              'R = R & ~(0x1 << n)',
              'R = R ^ (0x1 << n) (operacija XOR)',
              'R = R & (0x1 << n)'],
  'correct': 2,
  'question': 'Kako negiramo posamezen bit:'},
 {'anwsers': ['800 KB/s', '8 MB/s', '80 MB/s', '2 cm'],
  'correct': 1,
  'question': 'Koliko znaša maksimalna pasovna širina vodila ISA?'},
 {'anwsers': ['Koliko ns traja, preden se PCI naprava lahko odzove.',
              'Koliko μs lahko naprava poseduje vodilo.',
              'Koliko ciklov ure lahko naprava poseduje vodilo.',
              'Koliko časa potuje odbiti signal.'],
  'correct': 2,
  'question': 'Kaj pove časovnik latence pri PCI?'},
 {'anwsers': ['114 us', '132 us', '7.56 ms', '8.3 ms'],
  'correct': 1,
  'question': 'Koliko časa je bralna glava nad posameznim sektorjem pri disku '
              'z 7200RPM in 63 sektorji?'},
 {'anwsers': ['Naslovni, žetonski, podatkovni, rokovalni',
              'Sinhronizacijski, žetonski, podatkovni, rokovalni',
              'Žetonski, podatkovni, rokovalni, posebni',
              'Sinhronizacijski, žetonski, podatkovni, poštni'],
  'correct': 2,
  'question': 'Katere vrste paketov poznamo pri USB?'},
 {'anwsers': ['tretje stanje nam določa visoko impedanco (lahko povežemo več '
              'naprav na eno vodilo)',
              'ker je cenejši.',
              'ker ga lahko po potrebi onemogočimo.',
              'ker ga lahko uporabljajo le v treh državah na svetu.',
              'ker ima večje ojačenje.'],
  'correct': 0,
  'question': 'Zakaj je USB oddajnik tipa 3-state?'},
 {'anwsers': ['NOR je primeren za shranjevanje programske kode in do podatkov '
              'dostopa sekvenčno. ',
              'NOR ni primeren za shranjevanje programske kode in do podatkov '
              'dostopa sekvenčno. ',
              'NOR je primeren za shranjevanje programske kode in do podatkov '
              'ne dostopa sekvenčno.',
              'NOR ni primeren za shranjevanje programske kode in do podatkov '
              'ne dostopa sekvenčno.'],
  'correct': 2,
  'question': 'Katera trditev drži za NOR Flash?'},
 {'anwsers': ['PCI', 'PCI-X', 'PCI Express', 'AGP'],
  'correct': 2,
  'question': 'Katero vodilo uporabljajo grafične kartice danes za povezovanje '
              'v PC?'},
 {'anwsers': ['0',
              '2*f',
              'f (moreš vzorčiti vsaj z 2-kratno frekvenco, da ni aliasinga)',
              'f/2'],
  'correct': 2,
  'question': 'Katero frekvenco dobimo, če frekvenco f vzorčimo s frekvenco '
              '2*f?'},
 {'anwsers': ['Za pretvorbo analognega vhoda v digitalnega.',
              'Za pretvorbo digitalnega izhoda v analognega.',
              'Za pretvorbo analognega izhoda v digitalnega.',
              'Za pretvorbo digitalnega vhoda v analognega.'],
  'correct': 0,
  'question': 'Čemu mikrokrmilniki uporabljajo Schmittov prožilnik (Schmitt '
              'trigger)?'},
 {'anwsers': ['14%',
              '36%',
              '63%',
              '84%',
              '86% ( U = U0 * (1 - e^( -t / RC ) ) '],
  'correct': 4,
  'question': 'Koliko zraste napetost na kondenzatorju pri polnjenju če je t = '
              '2*RC'},
 {'anwsers': ['1V*cos(107t)',
              '1V*cos(107t+90°) U = L * di(t) / dt = (1 μH * 100mA * 10^7 * '
              'cos(107t+90°))',
              '10V*cos(107t)',
              '10V*cos(107t+90°)'],
  'correct': 1,
  'question': 'Tok na tuljavi (L = 1 μH) je i(t) = 100mA*sin(107t+90°). '
              'Kolikšna je napetost?'},
 {'anwsers': ['1:2',
              '2:1',
              '1:√2',
              '√2 : 1 ( 20 * log_10 (izhod / vhod) = 3dB )'],
  'correct': 3,
  'question': '3dB predstavlja razmerje moči:'},
 {'anwsers': ['Za napetostno ojačanje digitalnega signala.',
              'Za tokovno ojačanje digitalnega signala.',
              'Za ojačanje odbojev na liniji.',
              'Za vsak slučaj.'],
  'correct': 1,
  'question': 'Zakaj se uporablja linijski ojačevalnik (buffer / line '
              'driver)?'},
 {'anwsers': ['1', '2', '4', '6'],
  'correct': 2,
  'question': 'Koliko MOS tranzistorjev potrebujemo za CMOS buffer?'},
 {'anwsers': ['Stanje, pri katerem je vsaj en signal nizek.',
              'Stanje, pri katerem sta oba signala nizka.',
              'Stanje, pri katerem je (edini) signal nizek.',
              'Stanje, pri katerem so vsi trije signali nizki.'],
  'correct': 1,
  'question': 'Kaj predstavlja SE0 (Single-ended zero) pri standardu USB?'},
 {'anwsers': ['8',
              '6',
              '4',
              '2'],
  'correct': 2,
  'question': 'Koliko žic je v USB kablu?'},
{'anwsers': ['R = R | (0x1 << n)',
              'R = R & ~(0x1 << n)',
              'R = R ^ (0x1 << n)',
              'R = R & (1 << n)'],
  'correct': 1,
  'question': 'Kako nastavimo bit na mestu n na 0, ostale pa pustimo?'},
 {'anwsers': ['Na zahtevo lokalnih oblasti.',
              'Ker se je izkazalo, da globalna ne morejo nastavljati vseh '
              'naprav.',
              'Zaradi hitrih perifernih naprav.',
              'Zaradi principa lokalnosti.'],
  'correct': 2,
  'question': 'Zakaj so v PC-jih nekoč uvedli lokalna vodila?'},
 {'anwsers': ['Visoka napetost za brisanje.',
              'Za brisanje in programiranje ga je potrebno vzeti iz vezja.',
              'Lahko ga programiramo le enkrat.',
              'Brisati je možno le po eno celico naenkrat.'],
  'correct': 1,
  'question': 'Kaj je slabost EPROMa?'},
 {'anwsers': ['Od podatkov.', 'Od standarda.', 'Od naslova.', 'Od impedance.'],
  'correct': 2,
  'question': 'Od česa je odvisno, katera besedna linija pri polnilniku Flash '
              'se aktivira?'},
 {'anwsers': ['Tiste pod Nyquistovo.',
              'Tiste nad Nyquistovo.',
              'Tiste pod dvojno Nyquistovo.',
              'Tiste nad dvojno Nyquistovo.'],
  'correct': 1,
  'question': 'Katere frekvence je treba dušiti z nizkim (anti-aliasing) '
              'filtrom?'},
 {'anwsers': ['Lepše barve.',
              'Večja barvna globina.',
              'Zmanjšanje količine informacij.',
              'Večja paleta barv.'],
  'correct': 2,
  'question': 'Kakšen je smisel indirektnih barvnih sistemov (indeksirane '
              'barve)?'},
 {'anwsers': ['Monitor, ki deluje na principu taljenja ledu.',
              'Monitor, ki uporablja LED diode za polarizacijo svetlobe.',
              'Monitor, ki uporablja LED diode za osvetlitev.',
              'Monitor, ki uporablja LED diode za indikacijo, da je prižgan.'],
  'correct': 2,
  'question': 'Kaj pomeni »LED monitor«?'},
 {'anwsers': ['Ker lahko tako na disk spravimo več podatkov.',
              'Ker se disk vrti s konstantno hitrostjo.',
              'Zaradi kompatibilnosti s starejšimi napravami.',
              'Ker jih glava pri branju zazna.'],
  'correct': 3,
  'question': 'Zakaj so na magnetnih diskih pomembne prav vse spremembe '
              'magnetnega pretoka?'},
 {'anwsers': ['Napetost linearno upada.',
              'Napetost je konstantna.',
              'Napetost linearno raste. (Napetost je integral toka)',
              'Napetost raste s kvadratom.'],
  'correct': 2,
  'question': 'Kakšen je potek napetosti na kondenzatorju, če je tok '
              'konstanten in pozitiven?'},
 {'anwsers': ['ni odvisna od bremena in je večja od napetosti neobremenjenega '
              'vira',
              'ni odvisna od bremena in je manjša od napetosti neobremenjenega '
              'vira',
              'je odvisna od bremena in je večja od napetosti neobremenjenega '
              'vira',
              'je odvisna od bremena in je manjša od napetosti neobremenjenega '
              'vira'],
  'correct': 3,
  'question': 'Napetost na sponkah realnega vira:'},
 {'anwsers': ['√2:1', '2:1', '10:1 ( nauči se tabelco ) ', '100:1'],
  'correct': 2,
  'question': '20dB predstavlja razmerje razmerje moči'},
 {'anwsers': ['Schmitt trigger', 'Push-pull', 'Open drain', 'Pull-up'],
  'correct': 2,
  'question': 'Kako se imenuje tranzistor, ki mu je potrebno dodati upor?'},
 {'anwsers': ['Na 37%',
              'Na 14% ( U = U_0 * e ^(-t / RC) )',
              'Na 74%',
              'Na 63%'],
  'correct': 1,
  'question': 'Na koliko približno pade napetost pri praznjenju kondenzatorja '
              'v času t = 2RC? '},
 {'anwsers': ['0', '90°', '-90°', 'Odvisno od frekvence.'],
  'correct': 0,
  'question': 'Koliko znaša faza karakteristične impedance brezizgubne '
              'linije?'},
 {'anwsers': ['Zaradi hitrosti.',
              'Zaradi izboljšanja sinhronizacije.',
              'Zaradi zmanjšanja presluhov.',
              'Zaradi zmanjšanja števila signalov.'],
  'correct': 3,
  'question': 'Zakaj vodilo PCI uporablja časovno multipleksiranje?'},
 {'anwsers': ['Ker se poveča napetost na linijah D+ in D-.',
              'Ker se zmanjša napetost na liniji D+ ali D-.',
              'Ker se zmanjša napetost na linijah D+ in D-.',
              'Ker se poveča napetost na liniji D+ ali D-.'],
  'correct': 2,
  'question': 'Kako USB hub ugotovi, da se je naprava odklopila?'},
 {'anwsers': ['Ker je cenejši.',
              'Ker ga lahko po potrebi onemogočimo.',
              'Ker ga lahko uporabljajo le v treh državah na svetu.',
              'Ker ima večje ojačenje.'],
  'correct': 1,
  'question': 'Zakaj je buffer v USB oddajniku tipa tri-state?'},
 {'anwsers': ['pozitiven',
              'negativen',
              'odvisno od logične vrednosti celice',
              'ni naboja'],
  'correct': 1,
  'question': 'Kakšen naboj je v plavajoči plasti EPROM tranzistorja, kadar je '
              'sprogramiran?'},
 {'anwsers': ['Konstanta',
              'Aperiodičen',
              'Dušeno nihanje',
              'Harmoničen (ker ne odklopimo vira napetosti, sicer b/c)'],
  'correct': 3,
  'question': 'Kakšen je odziv sistema 2. reda na harmonični signal?'},
 {'anwsers': ['4', '10', '40', '100 (tabelca)'],
  'correct': 3,
  'question': 'Kolikšno je razmerje napetosti pri ojačenju 40dB?'},
 {'anwsers': ['Odvisno od situacije.',
              'UFE se poveča.',
              'UFE se zmanjša. (glej enačbo za UFE na UNE pa ne vpliva)',
              'Ne vpliva.'],
  'correct': 2,
  'question': 'Kako povečanje časa vzpona vpliva na UFE pri presluhih?'},
 {'anwsers': ['NE', 'IN', 'ALI', 'Ekskluzivni ALI'],
  'correct': 3,
  'question': 'Katero bitno operacijo moramo izvesti nad številoma 51 in 7, da '
              'dobimo 52?'},
 {'anwsers': ['0', '1', '-1', 'Inf'],
  'correct': 1,
  'question': 'Kolikšna je odbojnost na koncu vodila PCI?'},
 {'anwsers': ['3', '6   (20 * log10 (2^ n); n = 1)', '9', '12'],
  'correct': 1,
  'question': 'Koliko dB prinese vsak dodaten bit A/D pretvornika k razmerju '
              'med signalom in kvantizacijskim šumom?'},
 {'anwsers': ['Večja ločljivost in cenejši.',
              'Ima tudi digitalni izhod.',
              'Višja hitrost.',
              'Manjše potrebno število različnih vrednosti uporov.'],
  'correct': 0,
  'question': 'Kakšno prednost ima lestvični D/A pretvornik pred takim z '
              'uteženimi upori? (Odg.: Boljša resolucija, cenejši. Za en bit '
              'dodatne resolucije porabiš samo 2 upora.)'},
 {'anwsers': ['12cm, ', '24cm, ', '120cm, ', '240cm'],
  'correct': 0,
  'question': 'Kakšna je valovna dolžina Bluetooth signala?'},
  {'anwsers': ['Le liho število okvarjenih bitov.',
              'Sodo in liho število okvarjenih bitov.',
              'Le sodo število okvarjenih bitov.'],
  'correct': 0,
  'question': 'Katero napako zazna pariteta? (če uporabljamo 1 paritetni bit)'},
  {'anwsers': ['Lahko dosežemo maksimalno teoretično hitrost.',
              'Lahko dosežemo minimalno teoretično hitrost.',
              'Lahko dosežemo minimalno teoretično latenco.'],
  'correct': 0,
  'question': 'Kaj je prednost rafalnega načina pri PCI?'},
  {'anwsers': ['2*(cos(135°) + j*sin(135°))',
              '-1/2 * (cos(135°) + j*sin(135°))'],
  'correct': 0,
  'question': 'Koliko je 2*e^j*135°?'},
  {'anwsers': ['127','255','63','511'],
  'correct': 0,
  'question': 'Največ koliko naprav lahko naslovimo z USB?'},
  {'anwsers': ['2.4-2.48 GHz','5-8 MHz','1.2-1.8 MHz'],
  'correct': 0,
  'question': 'Kakšna je valovna dolžina Bluetooth-a?'},
  {'anwsers': [
    'Magnetne lahko samo berejo, vendar omogočajo večjo gosto; induktivne pa lahko pišejo in berejo.',
    'Induktivne lahko samo berejo, vendar omogočajo večjo gosto; magnetne pa lahko pišejo in berejo.'
  ],
  'correct': 0,
  'question': 'Zakaj imajo današnji diski kombinacijo magnetnih in induktivno bralno/pisalnih glav?'},
  {'anwsers': ['Ne vpliva.', 'Pozitivno.', 'Negativno.', 'Ni znano.'],
  'correct': 0,
  'question': 'Kako varianca merskega šuma R vpliva na Kalmanov gain?'},
  {'anwsers': ['7','8','16','6'],
  'correct': 0,
  'question': 'Koliko bitov ima USB naslov?'},
  {'anwsers': ['7','8','16','6'],
  'correct': 0,
  'question': 'Koliko bitov ima USB naslov?'},
  {'anwsers': [
    'Pri brezizgubni liniji.',
    'Pri izgubni liniji',
  ],
  'correct': 0,
  'question': 'Kdaj je karakteristična impedanca realna?'},
  {'anwsers': [
    'Karakteristično impedanca pada, faza se ne spremeni.',
    'Karakteristično impedanca naraste, faza se ne spremeni.',
    'Karakteristično impedanca naraste, faza se premakne za 15 stopinj.',
  ],
  'correct': 0,
  'question': 'Kaj se pri RC liniji zgodi z absolutno karakteristično impedanco in fazo ob večanju frekvence?'},
{'anwsers': [
    'Deluje po principu kondenzatorja, ki se mu spreminja kapacitativnost.',
    'Deluje po principu kondenzatorja, ki se mu spreminja naboj.',
  ],
  'correct': 0,
  'question': 'Kako deluje pospeškometer?'},
 {'anwsers': ['linearno vezje, ', 'RC vezje, ', 'LC vezje'],
  'correct': 1,
  'question': 'Katero vezje deluje kot nizki filter?'}]
  
